# 1. if Kconfig symbols of board defconfig file needs to modify then use this prj.conf 
# 2. pristine build reset/remove custom K config options so enable them in prj.conf 

#Enable QMC sensor
CONFIG_ENABLE_QMC5883L_SENSOR=y
CONFIG_QMC5883L_RANGE=2000
CONFIG_QMC5883L_ODR=50
CONFIG_QMC5883L_OSR=128

#Enable I2C
CONFIG_I2C=y
CONFIG_SENSOR=y

#Enable GPIO and logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_GPIO=y

#Logging in app_sources
CONFIG_ZSW_APP_LOG_LEVEL_INF=y


# Enable floating point support for the printf
CONFIG_CBPRINTF_FP_SUPPORT=y

# Enable (FPU) for calculations 
#CONFIG_FPU=y

# NVS
CONFIG_FLASH=y
CONFIG_FLASH_INIT_PRIORITY=40
CONFIG_FLASH_MAP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_STREAM_FLASH=y
CONFIG_STREAM_FLASH_ERASE=y
CONFIG_FLASH_MAP_LABELS=y

#Enable settings to save calibation data of qmc
CONFIG_SETTINGS=y
CONFIG_NVS=y

#Enable own qmc calibration driver,temporay option 
CONFIG_ENABLE_QMC_CALIBRATION=n
CONFIG_USE_RAW_MAGNETOMETER_DATA=y

#Enable built in driver for mpu6050, can enable options in menuconfig but they reset on pristine build
CONFIG_MPU6050=y
CONFIG_MPU6050_TRIGGER_NONE=y
CONFIG_MPU6050_GYRO_FS=2000


#Enbale own IMU driver
CONFIG_ENABLE_IMU=y

#update the log buffer size
CONFIG_LOG_BUFFER_SIZE=2048


#Enable built-in driver of ds3231
CONFIG_RTC=y
CONFIG_RTC_DS3231=y
CONFIG_COUNTER=n

#Enable RTC app code
CONFIG_ENABLE_RTC_TIME=y

#Enable display driver
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_DISPLAY_LOG_LEVEL_ERR=y

CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_SHELL=y
CONFIG_SHELL=y

CONFIG_LVGL=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
#CONFIG_LV_FONT_MONTSERRAT_14=y

CONFIG_LV_Z_BITS_PER_PIXEL=1

#CONFIG_LV_LOG_LEVEL_TRACE=y
CONFIG_LV_LOG_PRINTF=y

CONFIG_MPU_LOG_LEVEL_OFF=y                  # hides all those mpu_configure_region lines

CONFIG_MAIN_STACK_SIZE=8192

CONFIG_LV_Z_VDB_SIZE=16
CONFIG_LV_Z_FULL_REFRESH=n

CONFIG_LV_FONT_UNSCII_8=y
CONFIG_LV_FONT_DEFAULT_UNSCII_8=y
CONFIG_LV_FONT_MONTSERRAT_14=n
CONFIG_LV_COLOR_DEPTH_1=y 

CONFIG_LV_Z_BUFFER_ALLOC_DYNAMIC=y

